### PR TITLE
Switch to @truffle/fetch-and-compile

### PR DESCRIPTION
**Pull request by gnidan**
This PR proposes to replace the homespun usage of @truffle/source-fetcher + @truffle/compile-solidity with the [new] @truffle/fetch-and-compile package.

**Note**: the stable release of this package has a bug, so I've published a dist-tag release that contains the bugfix. We'll want to switch this to `latest` once this week's Truffle release happens (likely Thursday).

### CODE REVIEW

**Comment by gnidan** [comment]
@alaahd I can't add you as a reviewer until you accept the invite to join this org; pinging you via comment in the meantime

**Comment by alaahd** [comment]
@gnidan I have accepted the invitation !

**Comment by alaahd** [comment]
@gnidan sounds perfect !

**Review by alaahd — APPROVED** [review]

**Comment by gnidan** [comment]
Thanks @alaahd!

**Pull request merged**
